name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the directory
      uses: actions/checkout@v2

    - name: Install OPA
      run: |
        curl -L -o opa https://openpolicyagent.org/downloads/v0.35.0/opa_linux_amd64_static
        chmod 755 ./opa

    - name: lint
      run: |
        ./opa fmt --fail --list ./kubernetes

    - name: test
      run: |
        ./opa test ./kubernetes
